# Generated by Django 4.1.7 on 2023-03-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("_password", models.BinaryField(editable=True, max_length=128)),
                ("_salt", models.BinaryField(editable=True, max_length=4)),
            ],
        ),
    ]
