# Generated by Django 4.1.7 on 2023-05-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('npm', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('_password', models.BinaryField(editable=True, max_length=128)),
                ('_salt', models.BinaryField(editable=True, max_length=4)),
            ],
        ),
    ]
