# Generated by Django 4.1.7 on 2023-05-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('npm', models.TextField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('_password', models.BinaryField(editable=True, max_length=128)),
                ('_salt', models.BinaryField(editable=True, max_length=4)),
            ],
        ),
    ]
