# Generated by Django 4.1.7 on 2023-05-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
