# Generated by Django 4.1.7 on 2023-03-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="ID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
