version: '3.3'
services:
  Heizscheduler:
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      
    ports:
      - '5434:5432'
    volumes: 
      - Heizscheduler:/var/lib/postgresql/data
volumes:
  Heizscheduler:
    driver: local
