# Generated by Django 4.1.7 on 2023-05-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0003_user_username'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='bookers',
            field=models.ManyToManyField(to='auth_module.user'),
        ),
    ]
