# Generated by Django 4.1.7 on 2023-05-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_bookers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slot_selection_minute_multiplier',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='bookers',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='label',
        ),
    ]
