# Generated by Django 4.2.1 on 2023-05-08 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth_module", "0003_user_username"),
        ("schedule", "0003_remove_event_slot_selection_minute_multiplier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="is_preferred",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="schedule",
            name="owner",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth_module.user",
            ),
            preserve_default=False,
        ),
    ]
