# Generated by Django 4.1.7 on 2023-05-08 19:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0003_user_username'),
        ('schedule', '0003_remove_event_slot_selection_minute_multiplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_preferred', models.BooleanField(default=False)),
                ('datetime_range', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.daterange')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.event')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_module.user')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_preferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='owner',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='auth_module.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
